language: java
install: true

jdk:
  - oraclejdk8

secure: "AULo5rGvuDokzOf5kD/88jRbNNfCPR3oBsIQS2Qo9cGrac0kJ1uA1C4CYqh5R+XpWDxZCZoWTfKS2t6H+MrjKjzWl4/hdVf4FbkBQd7wwmdJnKqsXTOVpc8v21Eh6cqnb3Ob2h21sgmRZJD49tKeLiuyeRxIg+Cjjn+mEKd5Kx7ftEMXXlh7BZHNpZe2tFQ4r+qS6e5BSm2UfMmZr9H5k/+dzdwMJsjZaLlShs8SOh+BUpYMs8s2Ah9YoSCeY7oaex1pbbVhHwAtrwlgYjsycJG5HgPaa+3Re7Cde0VyEnRRRG7ivSnhLdpYEGwRZ7JyX44cMRPoTl0SzIgJaGx/JNXRE2o6rI3zllI6ZRnok8GUSNIiIlC1OPwLBt7qUhz2ki1HeH5ySFYbvj5cWYJKxTHu7OJUI7q/9Zc+dBfnJvlmxP3Ufh41dBkejYGuzRxMVlvg0ALmktAUl6xRMRl/OovWkl7gAF2sw0pZ8viMPxNQWmSXcsparoriTzkcgHF9T3xGA0cufPqLCzY4aUxRyY32+nxPRIvjJuwipf3A4Z+Mr+P4x+bazxz6qpQUIJ+I0KgaRuvO7UWWWxmJQgJAWkRvN0/SfgwJdTrQkAthWcNqCDXNbgHhpVnWjVouhD342U3axj/GJL+cr6UMQEwg/DH00vbsW6drkjBCdY0BU7o="
